server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asmaabarj/SmartBankSystem.git
          default-label: main
          search-paths: config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 