spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: asmaa123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true