server:
  port: 8090

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=0
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/ACCOUNT-SERVICE/**
          filters:
            - RewritePath=/ACCOUNT-SERVICE/(?<segment>.*), /$\{segment}
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"