server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: asmaa123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect