spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: asmaa123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082